---
name: Continuous Delivery
on:
  workflow_call:
    inputs:
      skip_what_if:
        default: false
        type: boolean
      governance-int-root:
        type: boolean
        default: true
      governance-landingzones:
        type: boolean
        default: true
      governance-landingzones-corp:
        type: boolean
        default: true
      governance-landingzones-online:
        type: boolean
        default: true
      governance-landingzones-local:
        type: boolean
        default: true
      governance-platform:
        type: boolean
        default: true
      governance-platform-connectivity:
        type: boolean
        default: true
      governance-platform-identity:
        type: boolean
        default: true
      governance-platform-management:
        type: boolean
        default: true
      governance-platform-security:
        type: boolean
        default: true
      governance-sandbox:
        type: boolean
        default: true
      governance-decommissioned:
        type: boolean
        default: true
      governance-platform-rbac:
        type: boolean
        default: true
      governance-platform-connectivity-rbac:
        type: boolean
        default: true
      governance-landingzones-rbac:
        type: boolean
        default: true
      core-logging:
        type: boolean
        default: true
      networking-hubnetworking:
        type: boolean
        default: true

jobs:
  whatif:
    name: What If
    runs-on:
      ubuntu-latest
    concurrency: mgmtb-tfstate
    environment: alzb-mgmtb-plan
    permissions:
      id-token: write
      contents: read
    if: ${{ !inputs.skip_what_if }}
    env:
      PARAMETERS_FILE_NAME: parameters.json

    steps:
      - name: Show inputs
        run: |
          Write-Host '${{ toJson(inputs) }}'
        shell: pwsh

      - name: Checkout Bicep Module
        uses: actions/checkout@v4

      - name: Get Bicep Variables
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-variables@main
        with:
          parameters_file_name: ${{ env.PARAMETERS_FILE_NAME }}

      - name: Install Bicep and Update Az Module
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-installer@main

      - name: OIDC Login to Tenant
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Check for First Deployment
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-first-deployment-check@main
        with:
          managementGroupId: ${{ env.MANAGEMENT_GROUP_ID }}

      - name: 'Plan: Governance-Intermediate Root'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-int-root }}
        with:
          name: 'governance-int-root'
          displayName: 'Governance-Intermediate Root'
          templateFilePath: 'templates/core/governance/mgmt-groups/int-root/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/int-root/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Landing Zones'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones }}
        with:
          name: 'governance-landingzones'
          displayName: 'Governance-Landing Zones'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Landing Zones Corp'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones-corp }}
        with:
          name: 'governance-landingzones-corp'
          displayName: 'Governance-Landing Zones Corp'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-corp/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-corp/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Landing Zones Online'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones-online }}
        with:
          name: 'governance-landingzones-online'
          displayName: 'Governance-Landing Zones Online'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-online/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-online/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Landing Zones Local'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones-local }}
        with:
          name: 'governance-landingzones-local'
          displayName: 'Governance-Landing Zones Local'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-local/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-local/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Platform'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform }}
        with:
          name: 'governance-platform'
          displayName: 'Governance-Platform'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Platform Connectivity'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-connectivity }}
        with:
          name: 'governance-platform-connectivity'
          displayName: 'Governance-Platform Connectivity'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-connectivity/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-connectivity/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Platform Identity'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-identity }}
        with:
          name: 'governance-platform-identity'
          displayName: 'Governance-Platform Identity'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-identity/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-identity/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Platform Management'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-management }}
        with:
          name: 'governance-platform-management'
          displayName: 'Governance-Platform Management'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-management/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-management/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Platform Security'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-security }}
        with:
          name: 'governance-platform-security'
          displayName: 'Governance-Platform Security'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-security/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-security/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Sandbox'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-sandbox }}
        with:
          name: 'governance-sandbox'
          displayName: 'Governance-Sandbox'
          templateFilePath: 'templates/core/governance/mgmt-groups/sandbox/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/sandbox/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Decommissioned'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-decommissioned }}
        with:
          name: 'governance-decommissioned'
          displayName: 'Governance-Decommissioned'
          templateFilePath: 'templates/core/governance/mgmt-groups/decommissioned/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/decommissioned/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Platform RBAC'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-rbac }}
        with:
          name: 'governance-platform-rbac'
          displayName: 'Governance-Platform RBAC'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/main-rbac.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/main-rbac.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Platform Connectivity RBAC'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-connectivity-rbac }}
        with:
          name: 'governance-platform-connectivity-rbac'
          displayName: 'Governance-Platform Connectivity RBAC'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-connectivity/main-rbac.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-connectivity/main-rbac.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Governance-Landing Zones RBAC'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones-rbac }}
        with:
          name: 'governance-landingzones-rbac'
          displayName: 'Governance-Landing Zones RBAC'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/main-rbac.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/main-rbac.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Core-Logging'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.core-logging }}
        with:
          name: 'core-logging'
          displayName: 'Core-Logging'
          templateFilePath: 'templates/core/logging/main.bicep'
          templateParametersFilePath: 'templates/core/logging/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'subscription'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'

      - name: 'Plan: Networking-Hub Networking'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.networking-hubnetworking }}
        with:
          name: 'networking-hubnetworking'
          displayName: 'Networking-Hub Networking'
          templateFilePath: 'templates/networking/hubnetworking/main.bicep'
          templateParametersFilePath: 'templates/networking/hubnetworking/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_CONNECTIVITY }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'subscription'
          firstRunWhatIf: 'false'
          whatIfEnabled: 'true'


  deploy:
    name: Deploy
    needs: whatif
    if: ${{ always() && !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
    runs-on:
      ubuntu-latest
    concurrency: mgmtb-tfstate
    environment: alzb-mgmtb-apply
    permissions:
      id-token: write
      contents: read
    env:
      PARAMETERS_FILE_NAME: parameters.json

    steps:
      - name: Show inputs
        run: |
          Write-Host '${{ toJson(inputs) }}'
        shell: pwsh

      - name: Checkout Bicep Module
        uses: actions/checkout@v4

      - name: Get Bicep Variables
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-variables@main
        with:
          parameters_file_name: ${{ env.PARAMETERS_FILE_NAME }}

      - name: Install Bicep and Update Az Module
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-installer@main

      - name: OIDC Login to Tenant
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: 'Deploy: Governance-Intermediate Root'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-int-root }}
        with:
          name: 'governance-int-root'
          displayName: 'Governance-Intermediate Root'
          templateFilePath: 'templates/core/governance/mgmt-groups/int-root/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/int-root/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Landing Zones'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones }}
        with:
          name: 'governance-landingzones'
          displayName: 'Governance-Landing Zones'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Landing Zones Corp'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones-corp }}
        with:
          name: 'governance-landingzones-corp'
          displayName: 'Governance-Landing Zones Corp'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-corp/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-corp/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Landing Zones Online'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones-online }}
        with:
          name: 'governance-landingzones-online'
          displayName: 'Governance-Landing Zones Online'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-online/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-online/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Landing Zones Local'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones-local }}
        with:
          name: 'governance-landingzones-local'
          displayName: 'Governance-Landing Zones Local'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-local/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/landingzones-local/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Platform'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform }}
        with:
          name: 'governance-platform'
          displayName: 'Governance-Platform'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Platform Connectivity'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-connectivity }}
        with:
          name: 'governance-platform-connectivity'
          displayName: 'Governance-Platform Connectivity'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-connectivity/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-connectivity/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Platform Identity'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-identity }}
        with:
          name: 'governance-platform-identity'
          displayName: 'Governance-Platform Identity'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-identity/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-identity/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Platform Management'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-management }}
        with:
          name: 'governance-platform-management'
          displayName: 'Governance-Platform Management'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-management/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-management/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Platform Security'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-security }}
        with:
          name: 'governance-platform-security'
          displayName: 'Governance-Platform Security'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-security/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-security/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Sandbox'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-sandbox }}
        with:
          name: 'governance-sandbox'
          displayName: 'Governance-Sandbox'
          templateFilePath: 'templates/core/governance/mgmt-groups/sandbox/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/sandbox/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Decommissioned'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-decommissioned }}
        with:
          name: 'governance-decommissioned'
          displayName: 'Governance-Decommissioned'
          templateFilePath: 'templates/core/governance/mgmt-groups/decommissioned/main.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/decommissioned/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Platform RBAC'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-rbac }}
        with:
          name: 'governance-platform-rbac'
          displayName: 'Governance-Platform RBAC'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/main-rbac.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/main-rbac.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Platform Connectivity RBAC'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-platform-connectivity-rbac }}
        with:
          name: 'governance-platform-connectivity-rbac'
          displayName: 'Governance-Platform Connectivity RBAC'
          templateFilePath: 'templates/core/governance/mgmt-groups/platform/platform-connectivity/main-rbac.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/platform/platform-connectivity/main-rbac.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Governance-Landing Zones RBAC'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.governance-landingzones-rbac }}
        with:
          name: 'governance-landingzones-rbac'
          displayName: 'Governance-Landing Zones RBAC'
          templateFilePath: 'templates/core/governance/mgmt-groups/landingzones/main-rbac.bicep'
          templateParametersFilePath: 'templates/core/governance/mgmt-groups/landingzones/main-rbac.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'managementGroup'

      - name: 'Deploy: Core-Logging'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.core-logging }}
        with:
          name: 'core-logging'
          displayName: 'Core-Logging'
          templateFilePath: 'templates/core/logging/main.bicep'
          templateParametersFilePath: 'templates/core/logging/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_MANAGEMENT }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'subscription'

      - name: 'Deploy: Networking-Hub Networking'
        uses: vrkondraju/alzb-mgmtb-templates/.github/actions/bicep-deploy@main
        if: ${{ inputs.networking-hubnetworking }}
        with:
          name: 'networking-hubnetworking'
          displayName: 'Networking-Hub Networking'
          templateFilePath: 'templates/networking/hubnetworking/main.bicep'
          templateParametersFilePath: 'templates/networking/hubnetworking/main.bicepparam'
          subscriptionId: '${{ env.SUBSCRIPTION_ID_CONNECTIVITY }}'
          resourceGroupName: ''
          location: '${{ env.LOCATION }}'
          deploymentType: 'subscription'

